FROM node:20

# CREATE AN APP DIRECTORY 
WORKDIR /src/APP

# Install app dependencies
COPY package*.json ./

RUN npm Install

# Bundle app source
COPY . .

RUN npm run build

EXPOSE 3000

# Command to run application
CMD ["npm","run", "start:prod"]
